site_name: Blockchain Pooling Analysis - Docs
nav:
        - Home: index.md
        - Parsers: parsers.md
        - Mappings: mappings.md
        - Metrics: metrics.md
        - Output: output.md
theme: readthedocs
